#include "slsa.hpp"
#include <chrono>
#include <ctime>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <nlohmann/json.hpp>

namespace fs = std::filesystem;
using json = nlohmann::json;

namespace cpfusa::slsa {

Level parse_level(const std::string& s) {
    if (s == "L1" || s == "1") return Level::L1;
    if (s == "L2" || s == "2") return Level::L2;
    if (s == "L3" || s == "3") return Level::L3;
    return Level::L4;
}
std::string level_str(Level l) {
    switch (l) {
        case Level::L1: return "SLSA-L1";
        case Level::L2: return "SLSA-L2";
        case Level::L3: return "SLSA-L3";
        default:        return "SLSA-L4";
    }
}
std::string status_str(Status s) {
    return (s == Status::Met) ? "satisfied" : "gap";
}

namespace {

//fusa:req REQ-SLSA001 REQ-SLSA002
std::vector<Requirement> baseline_requirements() {
    return {
        // SLSA Level 1
        {"SLSA-1.1", "L1", "Scripted build — fully automated build process",    true, true, true, true},
        {"SLSA-1.2", "L1", "Provenance available — build provenance accessible", true, true, true, true},
        {"SLSA-1.3", "L1", "SBOM present — Software Bill of Materials present",  true, true, true, true},
        // SLSA Level 2
        {"SLSA-2.1", "L2", "Build service — build runs on a dedicated service",  false, true, true, true},
        {"SLSA-2.2", "L2", "Provenance authenticated by build service",          false, true, true, true},
        {"SLSA-2.3", "L2", "Provenance generated by the build service",          false, true, true, true},
        {"SLSA-2.4", "L2", "Version controlled source — all sources tracked",   false, true, true, true},
        // SLSA Level 3
        {"SLSA-3.1", "L3", "Hardened build platform — immutable and isolated",  false, false, true, true},
        {"SLSA-3.2", "L3", "Non-falsifiable provenance from build service",      false, false, true, true},
        {"SLSA-3.3", "L3", "CODEOWNERS present for branch protection evidence",  false, false, true, true},
        {"SLSA-3.4", "L3", "Signed provenance — cryptographically signed",       false, false, true, true},
        {"SLSA-3.5", "L3", "Two-party review — all source changes reviewed",     false, false, true, true},
    };
}

Status detect_status(const Requirement& req, const fs::path& dir) {
    if (req.id == "SLSA-1.1")
        return fs::exists(dir / "CMakeLists.txt") ? Status::Met : Status::Gap;
    if (req.id == "SLSA-1.2")
        return fs::exists(dir / "provenance.json") ? Status::Met : Status::Gap;
    if (req.id == "SLSA-1.3")
        return fs::exists(dir / "sbom.json") ? Status::Met : Status::Gap;
    if (req.id == "SLSA-2.4")
        return fs::exists(dir / ".git") ? Status::Met : Status::Gap;
    if (req.id == "SLSA-3.3")
        return fs::exists(dir / ".github" / "CODEOWNERS") ? Status::Met : Status::Gap;
    if (req.id == "SLSA-3.4")
        return fs::exists(dir / "provenance.json.sig") ? Status::Met : Status::Gap;
    return Status::Gap;
}

bool is_required(const Requirement& r, Level lvl) {
    switch (lvl) {
        case Level::L1: return r.required_l1;
        case Level::L2: return r.required_l2;
        case Level::L3: return r.required_l3;
        default:        return r.required_l4;
    }
}

} // namespace

//fusa:req REQ-SLSA003
Report assess(const fs::path& dir, const std::string& project, Level lvl) {
    Report r;
    r.project = project;
    r.level   = level_str(lvl);

    auto now = std::chrono::system_clock::now();
    auto t   = std::chrono::system_clock::to_time_t(now);
    std::ostringstream ts;
    ts << std::put_time(std::gmtime(&t), "%Y-%m-%dT%H:%M:%SZ");
    r.generated_at = ts.str();

    for (auto req : baseline_requirements()) {
        if (!is_required(req, lvl)) continue;
        req.status = detect_status(req, dir);
        r.requirements.push_back(req);
        r.total++;
        if (req.status == Status::Met) r.satisfied++;
        else                           r.gap++;
    }
    return r;
}

void write_json(const fs::path& out, const Report& r) {
    json j;
    j["generatedAt"] = r.generated_at;
    j["project"]     = r.project;
    j["level"]       = r.level;
    j["summary"]     = {{"total", r.total}, {"satisfied", r.satisfied}, {"gaps", r.gap}};
    j["requirements"] = json::array();
    for (auto& req : r.requirements) {
        j["requirements"].push_back({
            {"id", req.id}, {"description", req.description},
            {"status", status_str(req.status)}
        });
    }
    std::ofstream f(out);
    f << j.dump(2);
}

void render_text(const Report& r) {
    std::cout << "SLSA Provenance Report — " << r.project << " [" << r.level << "]\n";
    std::cout << std::string(70, '-') << "\n";
    for (auto& req : r.requirements) {
        const char* m = (req.status == Status::Met) ? "[OK]" : "[  ]";
        std::cout << m << " " << req.id << "  " << req.description << "\n";
    }
    std::cout << std::string(70, '-') << "\n";
    std::cout << "Total: " << r.total << "  Satisfied: " << r.satisfied << "  Gap: " << r.gap << "\n";
}

} // namespace cpfusa::slsa
