#include "template_gen.hpp"
#include <filesystem>
#include <fstream>
#include <sstream>

namespace fs = std::filesystem;

namespace cpfusa::tmpl {

namespace {

std::string header(const std::string& title, const config::ProjectConfig& cfg) {
    return "# " + title + "\n\n"
         + "**Project:** " + cfg.project + "  \n"
         + "**Version:** " + cfg.version + "  \n"
         + "**Standard:** " + cfg.standard + " / " + cfg.asil + "  \n"
         + "**Date:** <!-- YYYY-MM-DD -->  \n"
         + "**Prepared by:** <!-- Name -->  \n\n"
         + "---\n\n";
}

} // namespace

std::string safety_plan_content(const config::ProjectConfig& cfg) {
    return header("Safety Plan", cfg)
         + "## 1. Scope\n\n<!-- Describe the system and its safety objectives. -->\n\n"
         + "## 2. Safety Goals\n\n| ID | Goal | ASIL |\n|---|---|---|\n| SG-001 | | " + cfg.asil + " |\n\n"
         + "## 3. Hazard and Risk Assessment (HARA)\n\nSee [HARA.md](HARA.md)\n\n"
         + "## 4. Safety Requirements\n\nRequirements are tracked in `.fusa-reqs.json`.\n"
         + "Run `cpfusa trace` to view the traceability matrix.\n\n"
         + "## 5. Verification and Validation\n\nSee [SVP.md](SVP.md)\n\n"
         + "## 6. Tool Qualification\n\nRun `cpfusa qualify` to generate the tool qualification evidence.\n\n"
         + "## 7. Configuration Management\n\nSee [SCMP.md](SCMP.md)\n\n"
         + "## 8. Quality Assurance\n\nSee [SQAP.md](SQAP.md)\n";
}

std::string test_evidence_content(const config::ProjectConfig& cfg) {
    return header("Test Evidence Report", cfg)
         + "## 1. Test Scope\n\n<!-- Describe what is being tested. -->\n\n"
         + "## 2. Test Environment\n\n"
         + "| Item | Value |\n|---|---|\n"
         + "| Compiler | <!-- e.g. clang++ 17.0 --> |\n"
         + "| OS | <!-- e.g. Ubuntu 22.04 --> |\n"
         + "| Build type | <!-- Release / RelWithDebInfo --> |\n\n"
         + "## 3. Test Results\n\n"
         + "| Test Suite | Pass | Fail | Skip |\n|---|---|---|---|\n| | | | |\n\n"
         + "## 4. Coverage\n\n"
         + "| Metric | Result | Required |\n|---|---|---|\n"
         + "| Statement | | 80% |\n"
         + "| Branch (Decision) | | 80% |\n"
         + "| MC/DC | | 80% (DAL-A/B) |\n\n"
         + "Generated by `cpfusa verify`. Run `cpfusa coverage` for LCOV report.\n";
}

std::string hara_content(const config::ProjectConfig& cfg) {
    return header("Hazard Analysis and Risk Assessment (HARA)", cfg)
         + "## 1. Operational Scenarios\n\n| ID | Scenario | Description |\n|---|---|---|\n| OS-01 | | |\n\n"
         + "## 2. Hazard Identification\n\n"
         + "| Hazard ID | Hazard | Operational Scenario | Effect |\n|---|---|---|---|\n| H-001 | | OS-01 | |\n\n"
         + "## 3. Risk Assessment\n\n"
         + "| Hazard ID | Severity | Exposure | Controllability | ASIL |\n|---|---|---|---|---|\n| H-001 | | | | " + cfg.asil + " |\n\n"
         + "## 4. Safety Goals\n\n"
         + "| SG ID | Safety Goal | Hazard | ASIL |\n|---|---|---|---|\n| SG-001 | | H-001 | " + cfg.asil + " |\n\n"
         + "*Severity: S0–S3 | Exposure: E0–E4 | Controllability: C0–C3*\n";
}

std::string svp_content(const config::ProjectConfig& cfg) {
    return header("Software Verification Plan (SVP)", cfg)
         + "## 1. Objectives\n\nVerify all software requirements are implemented and tested.\n\n"
         + "## 2. Verification Methods\n\n"
         + "| Method | Tool | When |\n|---|---|---|\n"
         + "| Static analysis | cpfusa analyze | Pre-commit |\n"
         + "| Unit test | Catch2 / GTest | CI |\n"
         + "| Integration test | <!-- --> | CI |\n"
         + "| Code review | GitHub PR | Per PR |\n\n"
         + "## 3. Coverage Criteria\n\nSee `cpfusa coverage` for LCOV-based structural coverage.\n\n"
         + "## 4. Traceability\n\nRun `cpfusa trace` to verify requirements ↔ tests.\n";
}

std::string scmp_content(const config::ProjectConfig& cfg) {
    return header("Software Configuration Management Plan (SCMP)", cfg)
         + "## 1. Controlled Items\n\nAll files tracked by Git. SBOM generated by `cpfusa release`.\n\n"
         + "## 2. Baseline Management\n\nReleases tagged with semver. Run `cpfusa sci` for the Software Configuration Index.\n\n"
         + "## 3. Change Control\n\nAll changes via GitHub Pull Requests with required review.\n\n"
         + "## 4. Audit Trail\n\nRun `cpfusa audit-pack` to produce an auditor ZIP bundle.\n";
}

std::string sqap_content(const config::ProjectConfig& cfg) {
    return header("Software Quality Assurance Plan (SQAP)", cfg)
         + "## 1. Coding Standards\n\nMISRA C++:2023, AUTOSAR C++14. Enforced by `cpfusa lint`.\n\n"
         + "## 2. Review Process\n\nAll changes reviewed via GitHub PR before merge to main.\n\n"
         + "## 3. Defect Management\n\nTracked via GitHub Issues. Problem reports: `cpfusa pr list`.\n\n"
         + "## 4. Metrics\n\nWeekly: `cpfusa check`, `cpfusa lint`, `cpfusa trace --req-coverage 80`.\n";
}

namespace {

bool write_file(const fs::path& dir, const std::string& name, const std::string& content) {
    std::ofstream f(dir / name);
    if (!f) return false;
    f << content;
    return true;
}

Result<std::monostate> gen_one(const fs::path& dir,
                               const config::ProjectConfig& cfg,
                               TemplateType t) {
    switch (t) {
        case TemplateType::SAFETY_PLAN:
            if (!write_file(dir, "SAFETY_PLAN.md", safety_plan_content(cfg)))
                return std::string("failed to write SAFETY_PLAN.md");
            break;
        case TemplateType::TEST_EVIDENCE:
            if (!write_file(dir, "TEST_EVIDENCE.md", test_evidence_content(cfg)))
                return std::string("failed to write TEST_EVIDENCE.md");
            break;
        case TemplateType::HARA:
            if (!write_file(dir, "HARA.md", hara_content(cfg)))
                return std::string("failed to write HARA.md");
            break;
        case TemplateType::SVP:
            if (!write_file(dir, "SVP.md", svp_content(cfg)))
                return std::string("failed to write SVP.md");
            break;
        case TemplateType::SCMP:
            if (!write_file(dir, "SCMP.md", scmp_content(cfg)))
                return std::string("failed to write SCMP.md");
            break;
        case TemplateType::SQAP:
            if (!write_file(dir, "SQAP.md", sqap_content(cfg)))
                return std::string("failed to write SQAP.md");
            break;
        case TemplateType::ALL:
            for (auto tt : {TemplateType::SAFETY_PLAN, TemplateType::TEST_EVIDENCE,
                             TemplateType::HARA, TemplateType::SVP,
                             TemplateType::SCMP, TemplateType::SQAP}) {
                auto r = gen_one(dir, cfg, tt);
                if (!is_ok(r)) return r;
            }
            break;
    }
    return std::monostate{};
}

} // anonymous namespace

//fusa:req REQ-TMPL004
Result<std::monostate> generate(const fs::path& dir,
                                const config::ProjectConfig& cfg,
                                TemplateType type) {
    return gen_one(dir, cfg, type);
}

} // namespace cpfusa::tmpl
